### ISSUE TITLE
not work on nginx

### ISSUE THREAD

**Issue by sickdaflip** [meanbee/magento-meanbee-pwa#15]
404 for serviceworker.js

**Comment by tgerulaitis** [comment]
@sickdaflip, that is most likely caused by the `location` rules you have in your Nginx configuration.

While the serviceworker.js endpoint appears as a JS file in the browser, it's actually rendered by a Magento controller action. We use a quirk in Magento's htaccess configuration, which tries to look up a real file for any assets, but falls back to using `index.php` if the file doesn't exist. However, in the Nginx configurations I've seen it's common to match assets by their extension, e.g. `location ~ \.(css|js)$`, and simply return a 404 if the file doesn't exist, without falling back to Magento rendering the result.

What's the config that you're using?

**Comment by sickdaflip** [comment]
@tgerulaitis, thx

i add "rewrite ^/serviceworker.js /index.php?serviceworker.js last;" and now working fine.
