### ISSUE TITLE
Is this project still active? if not - is there a commercial version?

### ISSUE THREAD

**Issue by seansan** [meanbee/magento-meanbee-pwa#21]
Is this project still active? if not - is there a commercial version?

**Comment by tgerulaitis** [comment]
Hi @seansan,

This project was always more of a proof of concept for us, when the service worker specification was new. Since then we've focused our efforts on Magento 2 and are no longer actively developing. However, we do respond to issues and questions, and will review and merge any pull requests.

The code is provided under the MIT license and we don't offer paid support for it, but if you're looking for help with a specific project, please feel free to fill out the form at https://www.space48.com/contact and we'll get back to you!

Thanks,
Tomas
