### ISSUE TITLE
Request to serviceworker = Slow

### ISSUE THREAD

**Issue by HRR1337** [meanbee/magento-meanbee-pwa#22]
Hi there,

Installed the extension and it works! happy with it. Though there is an issue regarding long loading time when it comes to: Request to serviceworker. 

![serviceworker](https://user-images.githubusercontent.com/4428675/40768674-460f15d6-64b6-11e8-8bc8-816f89384d0e.png)

Found also an answer, though dont have the knowledge to implement:

https://stackoverflow.com/questions/41758252/service-worker-slow-response-times

Thanks!

HRR

**Comment by tgerulaitis** [comment]
Hi @HRR1337 ,

Unfortunately, I can't say that we've experienced anything similar. The Stack Overflow post you've mentioned only affects service workers that have `ignoreSearch=true` parameter set for their cache lookups. The parameter isn't used in the service worker in this extension.

Have you customised your `serviceworker.js` file at all? What Magento version are you running? Does the issue only happen for assets (js, css files) or for page loads too (the initial document request)?

Tomas

**Comment by HRR1337** [comment]
Hi Tomas,

Thanks for the fast repley.

Havent touched the serviceworker.js. It happens for assets when its loaded from serviceworker.js 

if you hit chrome inspector, and then refresh the page, and in the column 'size', when there is ; from serviceworker, there you will notice the long requests. 

Can I sent you the test url?

Thanks!

**Comment by tgerulaitis** [comment]
Yeah, if you have one I could have a quick look!

**Comment by HRR1337** [comment]
Whats your e-mail? Thanks!

**Comment by tgerulaitis** [comment]
tomas.gerulaitis@meanbee.com

**Comment by tgerulaitis** [comment]
@HRR1337,

I had a look at the site and while I can replicate the issue, I think it might actually just be caused by the developer tools being active. By default, the developer tools has the "Disable cache" feature enabled. When I checked that off, requests went from taking 200ms to come back from the service worker, to 20ms. I'm not really sure which cache is affecting that, but something is.

I've also tried loading up a lot of different pages to fill up the cache and the response times haven't increased significantly, so it's definitely not related to cache size.

There are some suggestions in the comments here that this might be the case too: https://stackoverflow.com/questions/44106334/long-time-waiting-request-to-service-worker

What caused you to start investigating this? Have you experienced any unexpected slowdowns without developer tools open? Or was it just from looking at the Network waterfall? In case it's the latter, I think it's just because developer tools disable various caches.

Other than that, the service worker implementation here is very simple and naive, so there's not much code to take time on, but also not much in terms of performance improvements. We've upgraded the Magento 2 module to use workbox for the service worker, which might be a good thing to do for Magento 1 too.

Cheers,
Tomas

**Comment by HRR1337** [comment]
I'm allways trying to push the max of performance for my webshop, therefore, for every change i'm checking the performance :-)

Thanks for investigating. We have enabled it also on the live site and happy that people now can browse offline. We have another issue, but will make an new thread for that. thanks!
